name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to EC2 on develop branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-hostname.com >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v1
        with:
          server: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ~/.ssh/id_rsa # Use the SSH key you've set up earlier
          local: "." # Path to your local code to be deployed
          remote: "/path/to/Python" # Path on the EC2 instance to deploy to

      - name: SSH into EC2 and pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ~/.ssh/id_rsa
          script: |
            cd /path/to/Python
            git pull
