name: Push-to-EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to EC2 on develop branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $HOST_DNS >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_DNS: ${{ secrets.HOST_DNS }}

      - name: Push to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} 'cd /path/to/Python && git pull'
        env:
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
